// Percentage cards pool with consistent labels and icons
export const PERCENTAGE_CARDS_POOL = [
    { label: "Design Completion", iconCode: "pencil-alt" },
    { label: "Structural Analysis", iconCode: "building-columns" },
    { label: "MEP Coordination", iconCode: "cogs" },
    { label: "Energy Compliance", iconCode: "bolt" },
    { label: "Documentation", iconCode: "file-alt" },
    { label: "Site Progress", iconCode: "hard-hat" },
    { label: "Quality Assurance", iconCode: "clipboard-check" },
    { label: "Budget Tracking", iconCode: "wallet" },
    { label: "Client Approvals", iconCode: "handshake" },
    { label: "Safety Checks", iconCode: "shield-check" },
    { label: "Schedule Tracking", iconCode: "calendar-check" },
    { label: "Task Management", iconCode: "tasks" },
    { label: "Performance", iconCode: "chart-line" },
    { label: "Inspection", iconCode: "clipboard-list" },
    { label: "Compliance", iconCode: "hourglass-half" },
    { label: "Risk Assessment", iconCode: "exclamation-triangle" },
    { label: "Energy Audit", iconCode: "bolt-lightning" },
    { label: "Material Usage", iconCode: "boxes" },
    { label: "Procurement", iconCode: "truck" },
    { label: "Approval Status", iconCode: "thumbs-up" },
    { label: "Site Visits", iconCode: "map-marked-alt" },
    { label: "Coordination", iconCode: "users" },
    { label: "Client Feedback", iconCode: "comment-alt" },
    { label: "Training Progress", iconCode: "graduation-cap" },
    { label: "Documentation Review", iconCode: "file-alt" },
    { label: "Budget Allocation", iconCode: "wallet" },
    { label: "Change Orders", iconCode: "exchange-alt" },
    { label: "Issue Tracking", iconCode: "bug" },
    { label: "Inspection Compliance", iconCode: "clipboard-check" },
    { label: "Permit Status", iconCode: "file-signature" },
    { label: "Equipment Usage", iconCode: "cogs" },
    { label: "Resource Allocation", iconCode: "users-cog" },
    { label: "Site Safety", iconCode: "hard-hat" },
    { label: "Environmental Checks", iconCode: "leaf" },
    { label: "Waste Management", iconCode: "recycle" },
    { label: "Energy Efficiency", iconCode: "bolt" },
    { label: "Design Updates", iconCode: "pencil-alt" },
    { label: "Structural Updates", iconCode: "building-columns" },
    { label: "MEP Updates", iconCode: "cogs" },
    { label: "Project Handover", iconCode: "file-contract" },
    { label: "Final Review", iconCode: "clipboard-list" },
    { label: "Stakeholder Approval", iconCode: "handshake" },
    { label: "QA/QC", iconCode: "clipboard-check" },
    { label: "Audit Completion", iconCode: "search" },
    { label: "Inspection Reports", iconCode: "file-alt" },
    { label: "Construction Progress", iconCode: "hard-hat" },
    { label: "Design Validation", iconCode: "pencil-alt" },
    { label: "MEP Validation", iconCode: "cogs" },
    { label: "Safety Audits", iconCode: "shield-check" },
    { label: "Budget Review", iconCode: "wallet" },
    { label: "Final Approvals", iconCode: "thumbs-up" }
]

// Count cards pool with consistent labels and icons
export const COUNT_CARDS_POOL = [
    { label: "Walls", iconCode: "border-all" },
    { label: "Floors", iconCode: "th-large" },
    { label: "Roofs", iconCode: "house" },
    { label: "Columns", iconCode: "columns" },
    { label: "Beams", iconCode: "arrows-up-to-line" },
    { label: "Doors", iconCode: "door-closed" },
    { label: "Windows", iconCode: "window-maximize" },
    { label: "Stairs", iconCode: "person-walking" },
    { label: "Furniture", iconCode: "couch" },
    { label: "Ducts", iconCode: "wind" },
    { label: "Pipes", iconCode: "water" },
    { label: "Valves", iconCode: "faucet" },
    { label: "Lighting Fixtures", iconCode: "lightbulb" },
    { label: "Fire Protection", iconCode: "fire-extinguisher" },
    { label: "Generators", iconCode: "bolt" },
    { label: "Switchboards", iconCode: "plug" },
    { label: "Site Equipment", iconCode: "truck" },
    { label: "Terrain / Topography", iconCode: "mountain" },
    { label: "Curtain Walls", iconCode: "border-style" },
    { label: "Partitions", iconCode: "table-cells-large" },
    { label: "Sprinklers", iconCode: "spray-can" },
    { label: "HVAC Units", iconCode: "fan" },
    { label: "Electrical Panels", iconCode: "bolt-lightning" },
    { label: "Cable Trays", iconCode: "sitemap" },
    { label: "Fire Alarms", iconCode: "bell" },
    { label: "Facade Panels", iconCode: "layer-group" },
    { label: "Roof Hatches", iconCode: "door-open" },
    { label: "Site Lighting", iconCode: "lightbulb" },
    { label: "Security Cameras", iconCode: "video" },
    { label: "Fire Extinguishers", iconCode: "fire-extinguisher" },
    { label: "Generators Backup", iconCode: "bolt" },
    { label: "Switchboard Panels", iconCode: "plug" },
    { label: "HVAC Ducts", iconCode: "fan" },
    { label: "Water Pipes", iconCode: "water" },
    { label: "Valve Assemblies", iconCode: "faucet" },
    { label: "Roof Panels", iconCode: "layer-group" },
    { label: "Curtain Wall Frames", iconCode: "border-style" },
    { label: "Partition Walls", iconCode: "table-cells-large" },
    { label: "Electrical Conduits", iconCode: "bolt-lightning" },
    { label: "Cable Routes", iconCode: "sitemap" },
    { label: "Lighting Fixtures Backup", iconCode: "lightbulb" },
    { label: "Fire Alarms Backup", iconCode: "bell" },
    { label: "Windows Frames", iconCode: "window-maximize" },
    { label: "Doors Backup", iconCode: "door-closed" },
    { label: "Stair Rails", iconCode: "person-walking" },
    { label: "Furniture Sets", iconCode: "couch" },
    { label: "Site Tools", iconCode: "truck" },
    { label: "Terrain Models", iconCode: "mountain" },
    { label: "MEP Components", iconCode: "cogs" },
    { label: "Structural Components", iconCode: "building-columns" },
    { label: "Design Models", iconCode: "pencil-alt" },
    { label: "Inspection Tools", iconCode: "clipboard-check" },
    { label: "Project Documents", iconCode: "file-alt" }
]

// Function to randomize and assign numbers
export function getRandomizedCards<T extends { label: string; iconCode: string }>(
    pool: T[],
    count: number,
    valueKey: "percentage" | "count",
    min: number,
    max: number
) {
    const shuffled = [...pool].sort(() => Math.random() - 0.5)
    return shuffled.slice(0, count).map(item => ({
        ...item,
        [valueKey]: Math.floor(Math.random() * (max - min + 1)) + min
    }))
}

// Example usage:
const randomPercentages = getRandomizedCards(PERCENTAGE_CARDS_POOL, 10, "percentage", 10, 100)
const randomCounts = getRandomizedCards(COUNT_CARDS_POOL, 15, "count", 1, 20)

